[project]
name = 'chess-protocol'
description = ''
authors = ['Jadonamite']
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.gateway]
path = 'contracts/gateway.clar'
clarity_version = 2
epoch = 'latest'

[contracts.gateway_v2]
path = 'contracts/gateway_v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.chess-token_v2]
path = 'contracts/chess-token_v2.clar'
clarity_version = 4
epoch = 'latest'


[contracts.chess-token]
path = 'contracts/chess-token.clar'
clarity_version = 4
epoch = 'latest'

[contracts.chess-token-pro]
path = 'contracts/chess-tokenmainclar'
clarity_version = 4
epoch = 'latest'

[contracts.chess-game-pro]
path = 'contracts/chess-game.clar'
clarity_version = 4
epoch = 'latest'

[contracts.chess-escrow]
path = 'contracts/chess-escrow.clar'
clarity_version = 4
epoch = 'latest'

[contracts.logic]
path = 'contracts/logic.clar'
clarity_version = 4
epoch = 'latest'

[contracts.ranking]
path = 'contracts/ranking.clar'
clarity_version = 4
epoch = 'latest'

[contracts.registry]
path = 'contracts/registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.router]
path = 'contracts/router.clar'
clarity_version = 4
epoch = 'latest'

[contracts.timer]
path = 'contracts/timer.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'call_checker',
]
[repl.analysis.lints]


[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
