[project]
name = 'chess-protocol'
description = 'Chessify Protocol - Standalone Clarity Version'
authors = ['Jadonamite']
telemetry = true
cache_dir = './.cache'
requirements = []


[contracts.chess-game]
path = 'contracts/chess-game.clar'
clarity_version = 2
epoch = 'latest'

[repl.analysis]
passes = [
    'call_checker',
]

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
